id = "forester"
name = "Forester"
version = "0.0.1"
schema_version = 1
authors = ["Brian"]
description = "Minimal Forester language support for Zed"
repository = "https://github.com/brian/zed-forester"

[grammars.forester]
repository = "https://github.com/oberblastmeister/tree-sitter-forester"
rev = "b90e71e7c9f71ef8fc7ce9f404ecdc102681999d"

[language_servers.forester]
name = "forester lsp"
languages = ["Forester"]

[language_servers.forester.language_ids]
"Forester" = "forester"
