name = "Forester"
grammar = "forester"
path_suffixes = ["tree"]
brackets = [
  { start = "(", end = ")", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "{", end = "}", close = true, newline = true },
]
tab_size = 2
line_comments = ["% "]
