name = "Forester"
grammar = "forester"
path_suffixes = ["tree"]
brackets = [
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "{", end = "}", close = true, newline = true },
  { start = "'", end = "'", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false },
]
